-- MySQL Script generated by MySQL Workbench
-- Sat Feb  2 05:53:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` DEFAULT CHARACTER SET utf8 ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(255) NOT NULL,
  `dni_cliente` VARCHAR(50) NOT NULL,
  `direccion_cliente` VARCHAR(255) NOT NULL,
  `correo_cliente` VARCHAR(100) NULL,
  `codigo_cliente` INT(20) NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre_proveedor` VARCHAR(255) NOT NULL,
  `direccion_proveedor_1` VARCHAR(255) NULL,
  `direccion_proveedor_2` VARCHAR(255) NULL,
  `ciudad_proveedor` VARCHAR(50) NOT NULL,
  `pais_proveedor` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(10) NULL,
  `contacto_proveedor` VARCHAR(255) NULL,
  `numero_proveedor` VARCHAR(100) NULL,
  `numero_fax` VARCHAR(100) NULL,
  `numero_ruc` VARCHAR(50) NULL,
  `web_proveedor` VARCHAR(100) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `codigo_producto` VARCHAR(255) NOT NULL,
  `descripcion_producto` VARCHAR(255) NOT NULL,
  `precio_producto` FLOAT NULL,
  `stock_producto` INT NULL,
  `impuesto_producto` FLOAT NULL,
  `codigo_categoria` VARCHAR(255) NULL,
  `descripcion_categoria` VARCHAR(255) NULL,
  `subcodigo_categoria` VARCHAR(255) NULL,
  `subdescripcion_categoria` VARCHAR(255) NULL,
  `codigo_bodega` VARCHAR(100) NULL,
  `descripcion_bodega` LONGTEXT NULL,
  `codigo_fabricante` VARCHAR(100) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`vendedores` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre_vendedor` VARCHAR(255) NOT NULL,
  `dni_vendedor` VARCHAR(50) NOT NULL,
  `correo_vendedor` VARCHAR(100) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`ventas_contado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`ventas_contado` (
  `id_venta_normal` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_vendedor` INT NOT NULL,
  `cantidad_comprado_producto` INT NULL,
  `precio_producto` FLOAT NULL,
  `comentario_venta` LONGTEXT NULL,
  `codigo_compra` INT NULL,
  `descuento_compra` VARCHAR(45) NULL,
  `fecha_compra` DATE NULL,
  PRIMARY KEY (`id_venta_normal`),
  INDEX `ventas_normales_clientes_idx` (`id_cliente` ASC) ,
  INDEX `ventas_normales_productos_idx` (`id_producto` ASC) ,
  INDEX `ventas_normales_vendedores_idx` (`id_vendedor` ASC) ,
  CONSTRAINT `ventas_normales_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `stock`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ventas_normales_productos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `stock`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ventas_normales_vendedores`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `stock`.`vendedores` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`ventas_creditos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`ventas_creditos` (
  `id_venta_credito` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_vendedor` INT NOT NULL,
  `cantidad_comprado_producto` INT NULL,
  `precio_producto` FLOAT NULL,
  `comentario_venta` LONGTEXT NULL,
  `abono_compra` FLOAT NULL,
  `codigo_compra` INT NULL,
  `descuento_compra` VARCHAR(45) NULL,
  `fecha_compra` DATE NULL,
  `fecha_vencimiento` DATE NULL,
  PRIMARY KEY (`id_venta_credito`),
  INDEX `ventas_normales_clientes_idx` (`id_cliente` ASC),
  INDEX `ventas_normales_productos_idx` (`id_producto` ASC) ,
  INDEX `ventas_creditos_idx` (`id_vendedor` ASC) ,
  INDEX `ventas_codigo_compra` (`codigo_compra` ASC) ,
  CONSTRAINT `ventas_creditos_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `stock`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ventas_creditos_productos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `stock`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ventas_creditos`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `stock`.`vendedores` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`abonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`abonos` (
  `id_abono` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL,
  `total_abono` FLOAT NULL,
  `fecha_abono` DATE NULL,
  PRIMARY KEY (`id_abono`),
  INDEX `abonos_ventas_creditos_idx` (`id_cliente` ASC) ,
  CONSTRAINT `abonos_ventas_creditos`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `stock`.`ventas_creditos` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`proveedores_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`proveedores_productos` (
  `id_proveedor_producto` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_proveedor_producto`),
  INDEX `id_proveedores_productos_productos_idx` (`id_producto` ASC) ,
  INDEX `id_proveedores_productos_proveedores_idx` (`id_proveedor` ASC) ,
  CONSTRAINT `id_proveedores_productos_proveedores`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `stock`.`proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_proveedores_productos_productos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `stock`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
